- name: Add APT key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.2.asc
  tags: install

- name: Add APT repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
    state: present
  tags: install

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
  tags: install

- name: Install ca-certificates
  apt:
    name: ca-certificates
  tags: install

- name: Update APT
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 360

- name: Install mongodb package
  apt:
    name: mongodb-org
    state: present
  tags: install

- name: Configure service supervisor
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: install
