---
- name: Update apt
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 360

- name: Install ruby & rubygems
  apt:
    name: ['ruby-full', 'ruby-bundler', 'build-essential']
  tags: ruby
